name: hcapthcaptcha_fluttercha_flutter
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/OnurKaral/hcaptcha_flutter
repository: https://github.com/OnurKaral/hcaptcha_flutter

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
