name: hCaptcha_flutter
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/my_org/my_repo
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0